### ISSUE TITLE
Feature request: allow an array of providers

### ISSUE THREAD

**Issue by jonom** [Little-Giant/silverstripe-seeder#12]
To increase variety in seed content it would be great if you could specify either a single provider (as is the case now) or an array of providers. If an array is given then each new seed item could choose one at random.

```yaml
Seeder\Seeder:
  create:
    Page:
      count: 10
      fields:
        # Generate short and long titles
        Title:
          - faker(text,50)
          - faker(text,200)
        # Set a hero image on some pages but not all
        HeroImage:
          - random()
          - 0
```
