### ISSUE TITLE
Relation support for default_values

### ISSUE THREAD

**Issue by jonom** [Little-Giant/silverstripe-seeder#18]
I have a has_one Image relation on all pages which Seeder ignores by default. I can ensure this is populated by defining it in the 'create' definition, but I'd rather it randomly choose an image for all pages so I don't have to keep retyping it. Hoped this would work but doesn't appear to support relations:

```yml
Seeder:
  default_values:
    Page:
      MetaImage: random(Image) # Doesn't work
      Introduction: faker(paragraph) # Does work
```

Would it be possible to add relation support for default_values?
